"""add fields to user_specialization

Revision ID: 5e0da1a0175d
Revises: 779c2031096c
Create Date: 2024-06-21 21:22:23.485867

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e0da1a0175d"
down_revision: Union[str, None] = "779c2031096c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_specialization", sa.Column("price", sa.Integer(), nullable=True)
    )
    op.add_column(
        "user_specialization",
        sa.Column(
            "currency",
            postgresql.ENUM(
                "rub",
                "euro",
                "dollar",
                "yuan",
                name="currency",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "user_specialization",
        sa.Column(
            "payment_per",
            postgresql.ENUM(
                "hour", "project", name="paymentper", create_type=False
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "user_specialization",
        sa.Column(
            "is_ready_to_move",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "user_specialization",
        sa.Column(
            "is_ready_for_remote_work",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_specialization", "is_ready_for_remote_work")
    op.drop_column("user_specialization", "is_ready_to_move")
    op.drop_column("user_specialization", "payment_per")
    op.drop_column("user_specialization", "currency")
    op.drop_column("user_specialization", "price")
    # ### end Alembic commands ###
