"""Add event publish/unpublish routes

Revision ID: 0b5c6f0df4d1
Revises: 63ebf8310f3b
Create Date: 2024-07-26 13:14:33.430118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0b5c6f0df4d1"
down_revision: Union[str, None] = "63ebf8310f3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "published_at")
    # ### end Alembic commands ###
