"""Add unique constraint ip_address_event_id to EventView

Revision ID: c66ce1bcb079
Revises: 299d9e1a2b13
Create Date: 2024-07-10 11:48:44.771709

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c66ce1bcb079"
down_revision: Union[str, None] = "299d9e1a2b13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "view_ip_address_event_id_key",
        "event_view",
        ["ip_address", "event_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "view_ip_address_event_id_key", "event_view", type_="unique"
    )
    # ### end Alembic commands ###
