"""add timezone to user

Revision ID: 1bc91ffc9d36
Revises: 4212a61a9cfb
Create Date: 2024-06-12 13:58:17.333010

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bc91ffc9d36"
down_revision: Union[str, None] = "4212a61a9cfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("timezone_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "user", "timezone", ["timezone_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_timezone_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "timezone_id")
    # ### end Alembic commands ###
