"""ContactInfo

Revision ID: 3effe937f074
Revises: 9c9b11e1b54c
Create Date: 2024-07-31 11:34:31.867019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3effe937f074"
down_revision: Union[str, None] = "d0b6da51b808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_contact_info_id", table_name="user_contact_info")
    op.drop_table("user_contact_info")
    op.add_column(
        "user",
        sa.Column(
            "contact_info",
            postgresql.JSON(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "contact_info")
    op.create_table(
        "user_contact_info",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "email", sa.VARCHAR(length=320), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_number",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "phone_code",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="user_contact_info_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="user_contact_info_pkey"),
    )
    op.create_index(
        "ix_user_contact_info_id", "user_contact_info", ["id"], unique=False
    )
    # ### end Alembic commands ###
