"""add profile completeness

Revision ID: b508abbc778c
Revises: 39058c08452e
Create Date: 2024-06-11 08:59:51.080785

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b508abbc778c"
down_revision: Union[str, None] = "39058c08452e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profile_completeness",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "main_percentage", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "contacts_percentage",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "education_percentage",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "experience_percentage",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "mentorship_percentage",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profile_completeness_id"),
        "user_profile_completeness",
        ["id"],
        unique=False,
    )
    op.execute(
        """
            INSERT INTO user_profile_completeness (user_id)
            SELECT "user".id
            FROM "user"
            LEFT JOIN user_profile_completeness ON "user".id = user_profile_completeness.user_id
            WHERE user_profile_completeness.user_id is NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_profile_completeness_id"),
        table_name="user_profile_completeness",
    )
    op.drop_table("user_profile_completeness")
    # ### end Alembic commands ###
